- name: "Export Unifont font-name-var: 'unifont_font_name'"
  ansible.builtin.set_fact:
    unifont_font_name: 'Unifont'
  when: cfg_fonts_install_unifont_font

- name: "Export Terminus font-name-var: 'terminus_font_name'"
  ansible.builtin.set_fact:
    terminus_font_name: "Terminus"
  when: cfg_fonts_install_terminus_font

